version: '3.9'

services:
  postgres:
    image: postgres:14.5
    volumes:
      - ./db-dev-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: 'furnitureHelper'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: '1234'
  back:
    build:
      context: ./back/FurnitureHelper
      dockerfile: dev.Dockerfile
    ports:
      - '5000:5000'
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://*:5070
  front:
    build:
      context: ./front
      dockerfile: dev.Dockerfile
    volumes:
      - ./front/src:/app/src
      - ./front/public:/app/public
      - ./front/pages:/app/pages
    restart: always
    ports:
      - '3000:3000'
